### ISSUE TITLE
More providers for creating bundled_links.md 

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#40]
Context: https://github.com/RozeFound/mmc-export/issues/35#issuecomment-1142516016

If Curseforge is disabled with `--exclude-providers CurseForge`, use other providers for that data:
* Modrinth API
* Mod manifests (e.g. Fabric Mod Menu's "source" or "homepage" fields like #1)

And if some mods still don't get the data, just list them in the file without URLs, such as 
```
* ModName (link unknown)
```
(mod name can still be obtained from the manifest of the jar)

**Comment by RozeFound** [comment]
As of new Modrinth/CF policy, CF as a provider excluded from Modrinth totally, there is no reason to exclude CF manually.
Use Modrinth for that purpose is weird, because this "Bundled links" file created only for modrinth, which means this mods was no found on Modrinth anyway.
Mod Manifests already used to fetch GitHub links, but "Bundled links" is forming from mods without any providers, which means github links was not found in manifests.
Mods without any links must be in the end of the "Bundled links" file. And you encountered a bug, I'll fix it soon.

**Comment by Madis0** [comment]
> If resource already don't have any providers (download links) which what is happened when you excluded CF from search, it will be filtered on config parsing stage, or with another words, moved to overrides.

But can't it look for the download links in manifests in this stage, if CF is disabled?

**Comment by RozeFound** [comment]
Must be fixed with 7026bc2d5b46008ecf5881d30c02b9c8ec987690, please check

**Comment by Madis0** [comment]
Works as of 2.3.4
