### ISSUE TITLE
Packwiz export ignores config

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#61]
See https://github.com/Fabulously-Optimized/fabulously-optimized/releases/tag/v4.3.0-pw.1 for command and result. [The input zip used can be found here.](https://www.curseforge.com/minecraft/modpacks/fabulously-optimized/files/3975218)

I did provide the [mmc-export.toml](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/v4.3.0-pw.1/Modrinth/mmc-export.toml) but that wasn't reflected in the output.

**Comment by RozeFound** [comment]
Seems.. Weird to me. Everything must work... Anyway, will dig deeper into this tomorrow, I'm mentally dead now.

**Comment by RozeFound** [comment]
Well, the problem is in your config actually. Script looking for matches by name OR filename, so, when first, it matches Farsight Mod by name, removes it, and second time it can't find any matches because mod was just removed. I suggest you to delete `name` in first Farsight Mod entry in your config to fix the issue.
